<a href="https://colab.research.google.com/github/MGSev/Workbook-DLMAIIAC-Casual-Inference/blob/main/FEATURES_COLLAPSED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A Simple feed forward neural network 3 input (Grass_Background, Shape, Colour) 10 hidden neurons and 1 output

---



In [28]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch import sigmoid






Import the dataset



In [29]:
from pandas.io.api import read_csv
# Import the Dataset

df = pd.read_excel('cow_dataset2.xlsx')
print(df.head())

#extract features and label

# Extract features and labels
X = df[['Grass_Background', 'Shape', 'Colour']].values
y = df['Label'].values

#Convert to tensor
X_tensor = torch.tensor(df[['Grass_Background', 'Shape', 'Colour']].values, dtype=torch.float32)
y_tensor = torch.tensor(df['Label'].values, dtype=torch.float32).reshape(-1, 1)
print(X_tensor)
print(y_tensor)

   Grass_Background   Shape  Colour  Label
0                 1  0.0001  0.0001      1
1                 1  0.0001  0.0001      1
2                 1  0.0001  0.0001      1
3                 1  0.0001  0.0001      1
4                 1  0.0001  0.0001      1
tensor([[1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
      

Creating a class (three input layers, 10 hidden layer, one output layer)




In [30]:
## creating a class for simple FF-NN (three input layers, 10 hidden layer, one output layer)

class Net(nn.Module):
    def __init__(self, N_in, N_h, N_out):
        super(Net, self).__init__()
        self.linear1 = nn.Linear(N_in, N_h)
        self.linear2 = nn.Linear(N_h, N_out)
    def forward(self, x):
        oh = sigmoid(self.linear1(x))
        oo = sigmoid(self.linear2(oh))
        return oo




Creating actual network with three input neuron, 10 hidden neurons, one output neuron


In [31]:
# Creating a network with three input neuron, 10 hidden neurons, one output neuron
my_network = Net(3, 10, 1)
print(my_network)

# parameters can be seen in different ways

print(list(my_network.parameters()))

for p in list(my_network.parameters()):
    print(p)

my_network.state_dict()

for p, v in my_network.state_dict().items():
    print(p, v)

Net(
  (linear1): Linear(in_features=3, out_features=10, bias=True)
  (linear2): Linear(in_features=10, out_features=1, bias=True)
)
[Parameter containing:
tensor([[-0.5556,  0.4041,  0.5578],
        [ 0.0895,  0.2756, -0.3412],
        [ 0.0886, -0.4644,  0.2792],
        [-0.0296, -0.2925, -0.1019],
        [ 0.3665,  0.4095,  0.0342],
        [ 0.2850, -0.0809, -0.3069],
        [ 0.2339,  0.4870, -0.4457],
        [ 0.3745, -0.0609,  0.2778],
        [-0.4874,  0.1699,  0.2417],
        [ 0.5308,  0.2237,  0.4469]], requires_grad=True), Parameter containing:
tensor([-0.5412, -0.4748,  0.5539, -0.4369, -0.4849, -0.3981, -0.5660,  0.1912,
         0.2940, -0.0457], requires_grad=True), Parameter containing:
tensor([[-0.1178,  0.2515, -0.1751,  0.2390,  0.2168, -0.0047, -0.2628,  0.3090,
          0.0225, -0.0495]], requires_grad=True), Parameter containing:
tensor([0.2862], requires_grad=True)]
Parameter containing:
tensor([[-0.5556,  0.4041,  0.5578],
        [ 0.0895,  0.2756, -0.

Creating input and output of the network forward pass

In [32]:
# Creating input
x1 = X_tensor
print(x1)
# Creating output of the network (forward pass)
y1 = my_network(x1)
print(y1)

tensor([[1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [1.0000e+00, 1.0000e-04, 1.0000e-04],
        [0.0000e+00, 1.0000e-04, 1

Loss Function

In [33]:
# Loss function

error = nn.MSELoss()

y_compare = y_tensor
loss = error(y1, y_compare)
print(loss)
print(y_compare)
print(f"Loss: {loss.item()}")

tensor(0.2127, grad_fn=<MseLossBackward0>)
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
Loss: 0.21267415583133698


Forward and Backward Pass

In [35]:
# Forward pass
y1 = my_network(x1)

# Calculate loss
loss = error(y1, y_compare)

# Backward pass
loss.backward()

Weights Update

In [36]:
# Weights Update

learning_rate = 0.07
for f in my_network.parameters():
    f.data.sub_(f.grad.data * learning_rate)

Checking the loss after the first update

In [37]:
#Checking the loss
y1_new = my_network(x1)
loss_new = error(y1, y_compare)

print(f"Lossafter the firts update: {loss_new.item()}")

Lossafter the firts update: 0.21267415583133698



Training the loop


In [41]:
#Training the loop
my_network.zero_grad()
for epoch in range(2000):
  y_prediction = my_network(x1)
  loss = error(y_prediction, y_compare)
  my_network.zero_grad()
  loss.backward()
  for p in my_network.parameters():
    p.data = p.data - p.grad.data * learning_rate
    if epoch % 1000 == 0:
      print(f"Epoch: {epoch}, Loss: {loss.item():.6f}")


print(f"Loss after training: {loss.item():.6f}")

Epoch: 0, Loss: 0.004084
Epoch: 0, Loss: 0.004084
Epoch: 0, Loss: 0.004084
Epoch: 0, Loss: 0.004084
Epoch: 1000, Loss: 0.002721
Epoch: 1000, Loss: 0.002721
Epoch: 1000, Loss: 0.002721
Epoch: 1000, Loss: 0.002721
Loss after training: 0.002000


Feature Collapse

In [44]:
with torch.no_grad():
  H = sigmoid(my_network.linear1(X_tensor)).numpy
  print(H)
rank_input = np.linalg.matrix_rank(X_tensor.numpy())
print(rank_input)
rank_hidden = np.linalg.matrix_rank(H)
print(rank_hidden)

if rank_hidden < 10:
  print(f"Feature Collapse: from 10 to {rank_hidden}")
print(f"The network only leaned the feature shortcut (Grass_Backgound)")

<built-in method numpy of Tensor object at 0x790ada313f20>
2
1
Feature Collapse: from 10 to 1
The network only leaned the feature shortcut (Grass_Backgound)
